# Generated by Django 4.2.5 on 2023-10-01 15:54

import base_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='defaults/user/default-user.png', max_length=255, upload_to=base_app.models.photo_path),
        ),
    ]
